// Code generated by mockery. DO NOT EDIT.

package workerpool

import mock "github.com/stretchr/testify/mock"

// MockRunnable is an autogenerated mock type for the Runnable type
type MockRunnable struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *MockRunnable) Run() {
	_m.Called()
}

// NewMockRunnable creates a new instance of MockRunnable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunnable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunnable {
	mock := &MockRunnable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
