// Code generated by mockery. DO NOT EDIT.

package workerpool

import mock "github.com/stretchr/testify/mock"

// MockWorkerOption is an autogenerated mock type for the WorkerOption type
type MockWorkerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: pool
func (_m *MockWorkerOption) Execute(pool *pool) {
	_m.Called(pool)
}

// NewMockWorkerOption creates a new instance of MockWorkerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerOption {
	mock := &MockWorkerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
